flaskdash/app/models/__init__.py
from . import identity


flaskdash/app/models/identity.py
# Copyright 2014 SolidBuilds.com. All rights reserved
#
# Authors: Ling Thio <ling.thio@gmail.com>, Matt Hogan <matt@twintechlabs.io>

from flask_user import UserMixin
from flask_user.forms import RegisterForm
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, validators

from app.utils import *

# Define the User data model. Make sure to add the flask_user.UserMixin !!
class User(Reactor.orm.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)

    # User authentication information (required for Flask-User)
    email = db.Column(db.Unicode(255), nullable=False, server_default=u'', unique=True)
    email_confirmed_at = db.Column(db.DateTime())
    password = db.Column(db.String(255), nullable=False, server_default='')
    # reset_password_token = db.Column(db.String(100), nullable=False, server_default='')
    active = db.Column(db.Boolean(), nullable=False, server_default='0')

    # User information
    active = db.Column('is_active', db.Boolean(), nullable=False, server_default='0')
    first_name = db.Column(db.Unicode(50), nullable=False, server_default=u'')
    last_name = db.Column(db.Unicode(50), nullable=False, server_default=u'')

    # Relationships
    roles = db.relationship('Role', secondary='users_roles',
                            backref=db.backref('users', lazy='dynamic'))
    def has_role(self, role):
        for item in self.roles:
            if item.name == 'admin':
                return True
        return False

    def role(self):
        print(self.roles)
        for item in self.roles:
            return item.name

    def name(self):
        return self.first_name + " " + self.last_name


# Define the Role data model
class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, server_default=u'', unique=True)  # for @roles_accepted()
    label = db.Column(db.Unicode(255), server_default=u'')  # for display purposes


# Define the UserRoles association model
class UsersRoles(db.Model):
    __tablename__ = 'users_roles'
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'))
    role_id = db.Column(db.Integer(), db.ForeignKey('roles.id', ondelete='CASCADE'))


# Define the User registration form
# It augments the Flask-User RegisterForm with additional fields
class MyRegisterForm(RegisterForm):
    first_name = StringField('First name', validators=[
        validators.DataRequired('First name is required')])
    last_name = StringField('Last name', validators=[
        validators.DataRequired('Last name is required')])


# Define the User profile form
class UserProfileForm(FlaskForm):
    first_name = StringField('First name', validators=[
        validators.DataRequired('First name is required')])
    last_name = StringField('Last name', validators=[
        validators.DataRequired('Last name is required')])
    submit = SubmitField('Save')

flaskdash/app/__init__.py
from . import helpers
from . import utils
from . import shortcuts

from . import models
from . import graph
from . import schema

from . import views
from . import queue


flaskdash/app/commands/__init__.py
from . import trans

from . import shell
from . import query



flaskdash/app/graph/__init__.py
from . import agora

flaskdash/app/schema/__init__.py
from . import catalog

flaskdash/app/views/__init__.py
from . import admin
from . import oauth
from . import apis

from . import proc
from . import shell
from . import drive

from . import store
from . import nosql
from . import graph


flaskdash/app/views/apis.py
from app.shortcuts import *

# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@app.route'
api_blueprint = Blueprint('api', __name__, template_folder='templates')

@api_blueprint.route('/sample_call', methods=['POST'])
def sample_page():

    ret = {"sample return": 10}
    return(jsonify(ret), 200)

@api_blueprint.route('/slower')
@limiter.limit("1 per day")
def slow():
    return "24"

@api_blueprint.route('/faster')
def fast():
    return "42"


flaskdash/app/views/nosql.py
from app.shortcuts import 

#@Reactor.odm.schema(Post, content=ContentResource)
class PostResource(Reactor.odm.Resource):
    filters = {
        'title': [ops.Exact, ops.Startswith],
        'author_id': [ops.Exact],
    }
    rename_fields = {
        'author': 'author_id',
    }

@Reactor.odm.publish('posts', PostResource, '/posts/')
class PostView(Reactor.odm.Viewer):
    methods = [methods.Create, methods.Update, methods.Fetch, methods.List]

flaskdash/app/views/oauth.py
from app.shortcuts import *

flaskdash/app/views/proc.py
from app.shortcuts import 

@jsonrpc.method('App.index')
def index():
    return u'Welcome to Flask JSON-RPC'

flaskdash/app/views/query.py
from app.shortcuts import *

flaskdash/app/views/store.py
from app.shortcuts import 

flaskdash/app/views/views.py
from app.shortcuts import *

# Copyright 2017 Twin Tech Labs. All rights reserved

from flask import Blueprint, redirect, render_template, current_app
from flask import request, url_for, flash, send_from_directory, jsonify, render_template_string
from flask_user import current_user, login_required, roles_accepted

from app import db
from app.models.user_models import UserProfileForm, User, UsersRoles
import uuid, json, os
import datetime

# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@app.route'
main_blueprint = Blueprint('main', __name__, template_folder='templates')

# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/')
def member_page():
    if not current_user.is_authenticated:
        return redirect(url_for('user.login'))

    return render_template('pages/member_base.html')

# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_accepted('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('pages/admin_page.html')

@main_blueprint.route('/users')
@roles_accepted('admin')
def user_admin_page():
    users = User.query.all()
    return render_template('pages/admin/users.html',
        users=users)

@main_blueprint.route('/create_user', methods=['GET', 'POST'])
@roles_accepted('admin')
def create_user_page():
    form = UserProfileForm(request.form, obj=current_user)

    if request.method == 'POST':
        user = User.query.filter(User.email == request.form['email']).first()
        if not user:
            user = User(email=request.form['email'],
                        first_name=request.form['first_name'],
                        last_name=request.form['last_name'],
                        password=current_app.user_manager.hash_password(request.form['password']),
                        active=True,
                        email_confirmed_at=datetime.datetime.utcnow())
            db.session.add(user)
            db.session.commit()
        return redirect(url_for('main.user_admin_page'))
    return render_template('pages/admin/create_user.html',
                           form=form)

@main_blueprint.route('/delete_user', methods=['GET'])
@roles_accepted('admin')
def delete_user_page():
    try:
        user_id = request.args.get('user_id')

        db.session.query(UsersRoles).filter_by(user_id = user_id).delete()
        db.session.query(User).filter_by(id = user_id).delete()
        db.session.commit()

        flash('You successfully deleted your user!', 'success')
        return redirect(url_for('main.user_admin_page'))
    except Exception as e:
        flash('Opps!  Something unexpected happened.  On the brightside, we logged the error and will absolutely look at it and work to correct it, ASAP.', 'error')
        return redirect(request.referrer)

@main_blueprint.route('/pages/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.user_profile_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           current_user=current_user,
                           form=form)

flaskdash/app/templates/common/dark_base.html
{% extends "dark_layout.html" %}

flaskdash/app/templates/common/form_macros.html
{% macro render_field(field, label=None, label_visible=true, right_url=None, right_label=None) -%}
    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if field.type != 'HiddenField' and label_visible %}
            {% if not label %}{% set label=field.label.text %}{% endif %}
            <label for="{{ field.id }}" class="control-label">{{ label|safe }}</label>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>
{%- endmacro %}
 
{% macro render_checkbox_field(field, label=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ label }}
        </label>
    </div>
{%- endmacro %}
 
{% macro render_radio_field(field) -%}
    {% for value, label, checked in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}"{% if checked %} checked{% endif %}>
                {{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{% macro render_submit_field(field, label=None, tabindex=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    {#<button type="submit" class="form-control btn btn-default btn-primary">{{label}}</button>#}
    <input type="submit" value="{{label}}"
           {% if tabindex %}tabindex="{{ tabindex }}"{% endif %}
           >
{%- endmacro %}

flaskdash/app/templates/common/page_base.html
{% extends "layout.html" %}

flaskdash/app/templates/dark_layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Twin Tech Labs - CoreUI Flask Admin</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Place favicon.ico and apple-touch-icon(s) in the root directory -->
        <link rel="shortcut icon" href="images/favicon.ico">

        <!-- stylesheets -->
        <link href="{{ url_for('static', filename='css/flag-icon-css/css/flag-icon.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/simple-line-icons/css/simple-line-icons.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

        <!-- javascript -->
        <script src="{{ url_for('static', filename='js/popper.js/dist/umd/popper.min.js') }}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/pace-progress/pace.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/perfect-scrollbar/dist/perfect-scrollbar.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/@coreui/coreui/dist/js/coreui.min.js') }}"></script>

        <script src="https://code.highcharts.com/highcharts.js"></script>
        <script src="https://code.highcharts.com/modules/exporting.js"></script>
        <script src="https://code.highcharts.com/modules/export-data.js"></script>
    </head>
    <body>
        {% block body %}
        <div class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
          <header class="app-header navbar">
            <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
              <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.member_page') }}">
              FlaskDash
            </a>
            <a class="nav-link nav-link--rounded pull-right" style="margin-right: 10px;" href="{{ url_for('user.logout') }}">
              Sign out
            </a>
          </header>
          <div class="app-body">
            <div class="sidebar">
              <nav class="sidebar-nav">
                <ul class="nav">
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.member_page') }}">
                      <i class="nav-icon icon-speedometer"></i> Dashboard
                      <span class="badge badge-primary">NEW</span>
                    </a>
                  </li>
                  <li class="nav-item nav-dropdown">
                    <a class="nav-link nav-dropdown-toggle" href="#">
                      <i class="nav-icon icon-bell"></i> My Account</a>
                    <ul class="nav-dropdown-items">
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.user_profile_page') }}">
                          <i class="nav-icon icon-drop"></i> Profile</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.change_password') }}">
                          <i class="nav-icon icon-drop"></i> Password</a>
                      </li>
                    </ul>
                  </li>
                  <li class="nav-title">Administration</li>
                  <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.user_admin_page') }}">
                      <i class="nav-icon icon-drop"></i> Manage Users</a>
                  </li>
                </ul>
              </nav>
            </div>
          {% block pre_content %}{% endblock %}
          <main class="main">
          {# One-time system messages called Flash messages #}
          {% block flash_messages %}
              {%- with messages = get_flashed_messages(with_categories=true) -%}
                  {% if messages %}
                      {% for category, message in messages %}
                          {% if category=='error' %}
                              {% set category='danger' %}
                          {% endif %}
                          <div style="margin-bottom: -2px;" role="alert" class="alert alert-{{category}} alert-dismissible fade show">{{ message|safe }}</div>
                      {% endfor %}
                  {% endif %}
              {%- endwith %}
          {% endblock %}

          {% block content %}{% endblock %}
          </main>
          {% block post_content %}{% endblock %}

        {% endblock %}
        </div>
        <footer class="app-footer">
          <div>FlaskDash &copy; 2018 Twin Tech Labs</div>
          <div class="ml-auto">
            <span>Powered by</span>
            <a href="https://coreui.io">CoreUI</a>
            <span>(&copy; 2018 creativeLabs.)</span>
          </div>
        </footer>
      </div>
        <script>
            // Hide loader
            (function() {
                $(".alert").fadeTo(4000, 500).slideUp(500, function(){
                    $(".alert").slideUp(500);
                });
            })();
        </script>
    </body>
</html>

flaskdash/app/templates/flask_user/change_password.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}

{% from "common/form_macros.html" import render_field, render_submit_field %}
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item">My Account</li>
    <li class="breadcrumb-item active">Change Password</li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>
  <div class="container-fluid">
    <div class="animated fadeIn">
      <div class="card ">
        <form action="" method="POST" class="form" role="form">
          <div class="card-header ">
            <strong>Change Password</strong>
          </div>
          <div class="card-body ">
                {{ form.hidden_tag() }}
                <div class="form-group ">
                  <label for="nf-email ">Old Password</label>
                  <input class="form-control" id="old_password" name="old_password" tabindex="10" type="password" value="">
                </div>
                <div class="form-group ">
                  <label for="nf-password ">New Password</label>
                  <input class="form-control" id="new_password" name="new_password" tabindex="20" type="password" value="">
                </div>
                <div class="form-group ">
                  <label for="nf-password ">Retype Password</label>
                  <input class="form-control" id="retype_password" name="retype_password" tabindex="30" type="password" value="">
                </div>
          </div>
          <div class="card-footer ">
            <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
            <button type="reset " class="btn btn-sm btn-danger "><i class="fa fa-ban "></i> Reset</button>
          </div>
        </form>
      </div>
</div>
{% endblock %}

flaskdash/app/templates/flask_user/flask_user_base.html
{% extends "layout.html" %}


{% block pre_content %}
<div class="container">
    <div class="row">
        <div class="col-sm-7 col-md-6 col-lg-5 col-centered">
{% endblock %}


{% block post_content %}
        </div>
    </div>
</div>
{% endblock %}

flaskdash/app/templates/flask_user/forgot_password.html
{% extends "common/page_base.html" %}

{% block content %}

<div class="flex-row align-items-center app">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mx-4">
          <div class="card-body p-4">
            <form action="" method="POST" novalidate formnovalidate class="form" role="form">
                {{ form.hidden_tag() }}
                <h1>Forgot your password?</h1>
                <p class="text-muted">We'll send you a reminder.</p>
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="icon-user"></i>
                    </span>
                  </div>
                  <input class="form-control" id="email" name="email" tabindex="210" type="text" value="" placeholder="What is your email address?">
                </div>
                <button type="submit" class="btn btn-block btn-success">Reset password</button>
            </form>
          </div>
          <div class="card-footer p-4">
            <div class="row">
              <div class="col-12">
                <a href="/user/sign-in">Back to Log in</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flaskdash/app/templates/flask_user/login.html
{% extends "common/page_base.html" %}

{% block content %}

<div class="container app flex-row align-items-center">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card-group">
        <div class="card p-4">
          <div class="card-body">
            <form action="" method="POST" class="form" role="form">
              <input id="next" name="next" type="hidden" value="/">
              <input id="reg_next" name="reg_next" type="hidden" value="/">
              {{ form.hidden_tag() }}
              {# One-time system messages called Flash messages #}
              {% block flash_messages %}
                  {%- with messages = get_flashed_messages(with_categories=true) -%}
                      {% if messages %}
                          {% for category, message in messages %}
                              {% if category=='error' %}
                                  {% set category='danger' %}
                              {% endif %}
                              <p><font color="red">{{ message|safe }}</font></p>
                          {% endfor %}
                      {% endif %}
                  {%- endwith %}
              {% endblock %}
                <h1>Login</h1>
                <p class="text-muted">Sign In to your account</p>
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="icon-user"></i>
                    </span>
                  </div>
                  <input type="email" id="email" class="form-control" name="email" placeholder="Email">
                </div>
                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="icon-lock"></i>
                    </span>
                  </div>
                  <input type="password" id="password" class="form-control" name="password" placeholder="Password">
                </div>
                <div class="row">
                  <div class="col-6">
                    <input type="submit" class="btn btn-primary active" value="Sign in">
                  </div>
                  <div class="col-6 text-right">
                    <a href="/user/forgot-password" >Forgot password?</a>
                  </div>
                </div>
            </form>
          </div>
        </div>
        <div class="card text-white bg-primary py-5 d-md-down-none" style="width:44%">
          <div class="card-body text-center">
            <div>
              <h2>Sign up</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
              <a href="/user/register" class="btn btn-primary active mt-3">Register Now!</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flaskdash/app/templates/flask_user/member_base.html
{% extends 'flask_user/flask_user_base.html' %}

flaskdash/app/templates/flask_user/public_base.html
{% extends 'flask_user/flask_user_base.html' %}

flaskdash/app/templates/flask_user/register.html
{% extends "common/page_base.html" %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
<div class="flex-row align-items-center app">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card mx-4">
          <div class="card-body p-4">
            <form action="" method="POST" novalidate formnovalidate class="form" role="form">
                {{ form.hidden_tag() }}
                <h1>Register</h1>
                <p class="text-muted">Create your account</p>
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="icon-user"></i>
                    </span>
                  </div>
                  <input class="form-control" id="first_name" name="first_name" tabindex="240" type="text" value="" placeholder="What is your first name?">
                </div>
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="icon-user"></i>
                    </span>
                  </div>
                  <input class="form-control" id="last_name" name="last_name" tabindex="250" type="text" value="" placeholder="What is your last name?">
                </div>

                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">@</span>
                  </div>
                  <input class="form-control" id="email" name="email" tabindex="210" type="text" value="" placeholder="What is your email address?">
                </div>

                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="icon-lock"></i>
                    </span>
                  </div>
                  <input class="form-control" id="password" name="password" tabindex="260" type="password" value="" placeholder="Enter a password">
                </div>

                <div class="input-group mb-4">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="icon-lock"></i>
                    </span>
                  </div>
                  <input class="form-control" id="retype_password" name="retype_password" tabindex="270" type="password" value="" placeholder="Retype password">
                </div>
                <button type="submit" class="btn btn-block btn-success">Create Account</button>
            </form>
          </div>
          <div class="card-footer p-4">
            <div class="row">
              <div class="col-12">
                Already have an account?
                <a href="/user/sign-in">Sign in</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

flaskdash/app/templates/pages/admin/users.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}

{% from "common/form_macros.html" import render_field, render_submit_field %}

  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item">Admin</li>
    <li class="breadcrumb-item active">Users</li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>
  <div class="container-fluid">
    <div class="animated fadeIn">
      <div class="card ">
          <div class="card-header ">
            <strong>System Users</strong>
            <a href={{ url_for('main.create_user_page') }} class="btn btn-pill btn-sm btn-primary pull-right">Create User</a>
          </div>
          <div class="card-body ">
            <table class="table table-hover table-striped" style="padding-top: 50px;">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Role</th>
                  <th>Email</th>
                  <th>Confirmed</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {% for user in users %}
                <tr>
                  <td>{{user.name()}}</td>
                  <td>{{user.role()}}</td>
                  <td>{{user.email}}</td>
                  <td>{{user.email_confirmed_at}}</td>
                  <tD>
                    <div class="btn-group" role="group" aria-label="...">
                      <a href="{{ url_for('main.delete_user_page', user_id=user.id) }}"><i class="fa fa-remove"></i></a>
                    </div>
                  </tD>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="card-footer ">
          </div>
      </div>
</div>
{% endblock %}

flaskdash/app/templates/pages/user_profile_page.html
{% extends "common/dark_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}

{% from "common/form_macros.html" import render_field, render_submit_field %}
  <!-- Breadcrumb-->
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Home</li>
    <li class="breadcrumb-item">My Account</li>
    <li class="breadcrumb-item active">User Profile</li>
    <!-- Breadcrumb Menu-->
    <li class="breadcrumb-menu d-md-down-none">
      <div class="btn-group" role="group" aria-label="Button group">
        <a class="btn" href="#">
          <i class="icon-speech"></i>
        </a>
        <a class="btn" href="./">
          <i class="icon-graph"></i>  Dashboard</a>
        <a class="btn" href="#">
          <i class="icon-settings"></i>  Settings</a>
      </div>
    </li>
  </ol>
  <div class="container-fluid">
    <div class="animated fadeIn">
      <div class="card ">
        <form action="" method="POST" class="form" role="form">
          <div class="card-header ">
            <strong>User Profile</strong>
          </div>
          <div class="card-body ">
                {{ form.hidden_tag() }}
                <div class="form-group ">
                  <label for="nf-email ">First name</label>
                  <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Enter first name" value="{{current_user.first_name}}">
                </div>
                <div class="form-group ">
                  <label for="nf-password ">Last name</label>
                  <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Enter last name" value="{{current_user.last_name}}">
                </div>
          </div>
          <div class="card-footer ">
            <button type="submit " class="btn btn-sm btn-primary "><i class="fa fa-dot-circle-o "></i> Submit</button>
            <button type="reset " class="btn btn-sm btn-danger "><i class="fa fa-ban "></i> Reset</button>
          </div>
        </form>
      </div>
</div>
{% endblock %}